## Intro to Vectors with python numpy and pytorch

In [1]:
# Reader may need to install numpy to make the
# import statement work.
import numpy as np
import sys
print("python version = {}\nnumpy version = {}".format(sys.version,
                                                       np.__version__))

python version = 2.7.10 (default, Feb  6 2017, 23:53:20) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
numpy version = 1.16.5


In [2]:
# A vector is an 1-dimensional array of numbers.
# E.g., input hardness vector of our cat brain model
v = np.array([0.11, 0.01, 0.98, 0.12, 0.98, 0.85, 0.03,
              0.55, 0.49, 0.99, 0.02, 0.31, 0.55, 0.87,
              0.63])

# Individual elements of the vector can be accessed through
# the square bracket operator with indices of the desired
# element  within thosesquare brackets.
# Index starts from zero, not one.
first_element = v[0]
third_element = v[2]
print("first element = {} third_element = {}".\
      format(first_element, third_element))

# Negative indices are to be counted from the end of array.
# E.g., -1 refers to the last array element.
#       -2 refers to the second from last element.
last_element = v[-1]
second_last_element = v[-2]
print("last_element = {} second_last_element = {}".\
      format(last_element, second_last_element))

# A range of elements can be sliced off a vector using the
# colon operator
second_to_fifth_elements = v[1:4]
print("second_to_fifth_elements: {}".format(second_to_fifth_elements))

# If nothing is specified on the left of the arrow, it implies beginning
# of array.
# If nothing is specified after the  colon it implies end of array.
first_to_third_elements = v[:2]
last_two_elements = v[-2:]
print("first_to_third_elements: {}  Last two elements: {}".\
      format(first_to_third_elements, last_two_elements))

# Size of the vector
num_elements_in_v = len(v)
print("Number of elements in v: {}".format(num_elements_in_v))

first element = 0.11 third_element = 0.98
last_element = 0.63 second_last_element = 0.87
second_to_fifth_elements: [0.01 0.98 0.12]
first_to_third_elements: [0.11 0.01]  Last two elements: [0.87 0.63]
Number of elements in v: 15


In [3]:
# Now we will do the same things with a different package (PyTorch).
# Reader may need to install pyTorch to make this import work
from __future__ import print_function
import torch

print("PyTorch version = {}".format(torch.__version__))

PyTorch version = 1.2.0


In [4]:
# A torch tensor represents a multi-dimensional array (element type
# will be float by default, here we are forcing float64, aka double).
# A vector is a special case (1D array). It can be initialized
# directly by specifying the values.
u = torch.tensor([0.11, 0.01, 0.98, 0.12, 0.98, 0.85, 0.03,
                  0.55, 0.49, 0.99, 0.02, 0.31, 0.55, 0.87,
                  0.63], dtype=torch.float64)

# A torch tensor can also be initialized from a numpy array.
# Here we will initialize a tensor v1 from the numpy array v 
# defined above.
v1 = torch.from_numpy(v)

# One can add subtract tensors. Here we do diff = v1 - u.
# Since v1 and u contain the same values, their difference
# is all zeros.
diff = v1.sub(u)
print(u)
print(v1)
print(diff)

# torch tensors can be converted to numpy arrays too.
u1 = u.numpy()
print(u1 - v)

tensor([0.1100, 0.0100, 0.9800, 0.1200, 0.9800, 0.8500, 0.0300, 0.5500, 0.4900,
        0.9900, 0.0200, 0.3100, 0.5500, 0.8700, 0.6300], dtype=torch.float64)
tensor([0.1100, 0.0100, 0.9800, 0.1200, 0.9800, 0.8500, 0.0300, 0.5500, 0.4900,
        0.9900, 0.0200, 0.3100, 0.5500, 0.8700, 0.6300], dtype=torch.float64)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=torch.float64)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
