In [5]:
# Now we will do the same things with a different package (PyTorch).
# Reader may need to install pyTorch to make this import work
from __future__ import print_function
import torch

print("PyTorch version = {}".format(torch.__version__))

# A torch tensor represents a multi-dimensional array (element type
# will be float by default, here we are forcing float64, aka double).
# A vector is a special case (1D array). It can be initialized
# directly by specifying the values.
u = torch.tensor([0.11, 0.01, 0.98, 0.12, 0.98, 0.85, 0.03,
                  0.55, 0.49, 0.99, 0.02, 0.31, 0.55, 0.87,
                  0.63], dtype=torch.float64)

# A torch tensor can also be initialized from a numpy array.
# Here we will initialize a tensor v1 from the numpy array v 
# defined above.
v1 = torch.from_numpy(v)

# One can add subtract tensors. Here we do diff = v1 - u.
# Since v1 and u contain the same values, their difference
# is all zeros.
diff = v1.sub(u)
print(u)
print(v1)
print(diff)

# torch tensors can be converted to numpy arrays too.
u1 = u.numpy()
print(u1 - v)

PyTorch version = 1.1.0
tensor([0.1100, 0.0100, 0.9800, 0.1200, 0.9800, 0.8500, 0.0300, 0.5500, 0.4900,
        0.9900, 0.0200, 0.3100, 0.5500, 0.8700, 0.6300], dtype=torch.float64)
tensor([0.1100, 0.0100, 0.9800, 0.1200, 0.9800, 0.8500, 0.0300, 0.5500, 0.4900,
        0.9900, 0.0200, 0.3100, 0.5500, 0.8700, 0.6300], dtype=torch.float64)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=torch.float64)
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
